PaloAltoNetworks/prisma-cloud-go

- integration/structs.go
Add a support to manage slack notification when an integration is created
We work on this change to implement it in the terraform provider.
I test it on the account of my company.
code used for the test:
```golang
package main
import (
prismacloud "github.com/paloaltonetworks/prisma-cloud-go"
"github.com/paloaltonetworks/prisma-cloud-go/integration"
)
func main() {
client := prismacloud.Client{}
err := client.Initialize("creds.json")
if err != nil {
panic(err)
}
err = integration.Create(&client, integration.Integration{
Name: "GolangTest",
Description: "Test TestTest",
IntegrationType: "slack",
Enabled: true,
IntegrationConfig: integration.IntegrationConfig{WebHookUrl: "https://hooks.slack.com/services/.../.../..."},
})
if err != nil {
panic(err)
}
}
```
- New feature (non-breaking change …
> Add a support for slack notification in integration

- cloud/account/org/const.go
- cloud/account/org/funcs.go
- cloud/account/org/structs.go
> Ocisupport

- rql/search/const.go
- rql/search/structs.go
Added support to save network seaches
> Added support for network saved search

- policy/const.go
- rql/search/const.go
- rql/search/funcs.go
- rql/search/structs.go
- timerange/struct.go
Added support for IAM policy and IAM RQL search
- Added changes in timerange/struct.go -> SetType() and SetValue() functions because in API, datatype of 'Value' parameter for timerange to_now is string and not a struct
> Adding support for IAM policy, Anomaly policy and IAM RQL search

- user/role/structs.go
Added a block of additional attributes.
"additionalAttributes": {
"onlyAllowCIAccess"
"onlyAllowComputeAccess"
"hasDefenderPermissions"
"onlyAllowReadAccess"
},
> Added support for compute capabilities

- report/const.go
- report/funcs.go
- report/structs.go
- timerange/struct.go
Adding support for alert and compliance reports
- Added a change in timerange/struct.go -> setValue() function because in API, datatype of 'Value' parameter for timerange to_now is string and not a struct
> Adding support for alert and compliance reports

- integration/structs.go
Adding support for google_cscc integration
> Adding support for google_cscc integration

- cloud/account/org/structs.go
Making changes to AWS-org-hierarchy selection
> adding changes to structs

- policy/structs.go
Changes in policy recommendations schema
> Recommendation

- cloud/account/org/structs.go
Adding struct for azure hierarchy
> Adding struct for azure hierarchy

- policy/structs.go
> custom build and custom code security policy struct

- anomalySettings/anomalyTrustedList/const.go
- anomalySettings/anomalyTrustedList/funcs.go
- anomalySettings/anomalyTrustedList/structs.go
- anomalySettings/const.go
- anomalySettings/funcs.go
- anomalySettings/structs.go
anomaly setting and anomaly trusted list
> anomaly setting and anomaly trusted list

- user/role/const.go
Added Developer and NetSecOps user-role types
> Added Developer and NetSecOps user-role types

- policy/const.go
Added critical and informational severity support for policy
> Added critical and informational severity support for policy

- policy/const.go
Added policy rule type NetworkConfig
> Added policy rule type networkconfig

- cloud/account-v2/const.go
- cloud/account-v2/externalid/const.go
- cloud/account-v2/externalid/funcs.go
- cloud/account-v2/externalid/structs.go
- cloud/account-v2/funcs.go
- cloud/account-v2/org/const.go
- cloud/account-v2/org/funcs.go
- cloud/account-v2/org/structs.go
- cloud/account-v2/structs.go
- cloud/account-v2/supportedFeatures/const.go
- cloud/account-v2/supportedFeatures/funcs.go
- cloud/account-v2/supportedFeatures/structs.go
> aws cas changes

- .idea/workspace.xml
- cloud/account/funcs.go
- ip-address/const.go
- ip-address/funcs.go
- ip-address/structs.go
> RLP-97162: Add support for IP-Login-Allow-List

- settings/enterprise/structs.go
Enterprise settings audit log struct
> Enterprise settings audit log struct

- error.go
- trusted-alert-ip/const.go
- trusted-alert-ip/funcs.go
- trusted-alert-ip/structs.go
> trusted-alert-ips struct

- cloud/account-v2/externalid/const.go
- cloud/account-v2/externalid/funcs.go
- cloud/account-v2/externalid/structs.go
- cloud/account-v2/funcs.go
- cloud/account-v2/structs.go
> storage uuid struct

- notification-template/const.go
- notification-template/funcs.go
- notification-template/structs.go
> RLP-97165:Notification Template Support from terraform provider

- error.go
- resource-list/const.go
- resource-list/funcs.go
- resource-list/structs.go
Added support for resource lists.
> Added support for resource lists

- policy/structs.go
> Added actions attribute to policy remediation

- rql/search/structs.go
Added Heuristic Search for config and audit event queries
Added the boolean flag for heuristic Search for config and audit event queries
SAM Stack
> Heuristic Search
